server:
  servlet:
    context-path: /payment-service
  port: 8086

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

      properties:
        schema.registry.url: http://localhost:8081

    listener:
      ack-mode: manual

  datasource:
    url: jdbc:postgresql://localhost:5432/edpp
    username: edpp
    password: edpp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: payment-service